# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cfb2ba679fe73abdfb91a3faf49401b369454f7e39dfbbce7049db5ef99384b35582189e0a6f0f3a46f4f119bcd06758d3bc662df027f4477f05ecd2ab1aee4

test:
  secret_key_base: b3aeeafdec4c38417019dcbbca7fdefbd3baa558b4adecc04a64dcd1821ad9e1eb5254c0b739fecb5e56e33920e7ec48575e49a6224f698d3cc754a6fe2d2e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
